bot:
  name: ${TG_BOT_NAME}
  token: ${TG_KEY}
spring:
  application:
    name: tgStatBot

  datasource:
    hikari:
      max-lifetime: 550000
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
